### ISSUE TITLE
Can't find modules

### ISSUE THREAD

**Issue by Tabrizian** [fandogh/nuxt-helpers#6]
Hello Pooya :),

I get this error when I try to use this library.

```bash
{ Error: Cannot find module '/home/iman/Documents/Git/nuxt-start/node_modules/nuxt-helpers/lib/bootstrap-vue/_helper.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at install (/home/iman/Documents/Git/nuxt-start/node_modules/nuxt-helpers/lib/install.js:54:18)
    at helpers.forEach.m (/home/iman/Documents/Git/nuxt-start/node_modules/nuxt-helpers/lib/install.js:35:23)
    at Array.forEach (native)
    at wrap (/home/iman/Documents/Git/nuxt-start/node_modules/nuxt-helpers/lib/install.js:34:13)
    at Object.<anonymous> (/home/iman/Documents/Git/nuxt-start/nuxt.config.js:3:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19) code: 'MODULE_NOT_FOUND' }
```
What's the problem with my below configuration:
**nuxt.config.js**
```js
const NuxtHelpers = require('nuxt-helpers');

module.exports = NuxtHelpers(['bootstrap-vue'], {

});
```

And here is my **package.json**
```js
{
  "name": "Hello World in Nuxt :)",
  "version": "1.0.0",
  "description": "Nuxt.js project",
  "author": "Iman Tabrizian <Tabrizian@outlook.com>",
  "private": true,
  "dependencies": {
    "axios": "^0.16.0",
    "bootstrap-vue": "^0.11.1",
    "js-cookie": "^2.1.4",
    "mini-toastr": "^0.6.5",
    "nuxt": "latest",
    "nuxt-helpers": "^0.7.0",
    "vue-notifications": "^0.7.6"
  },
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "css-loader": "^0.28.0",
    "eslint": "^3.15.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.1",
    "eslint-plugin-standard": "^2.0.1",
    "node-sass": "^4.5.2",
    "sass-loader": "^6.0.3",
    "vue-style-loader": "^2.0.5"
  }
}
```

**Comment by pi0** [comment]
Hi iman. i think helper name is `bootstrap`

**Comment by Tabrizian** [comment]
That's it :+1:

**Comment by lgs** [comment]
... since following versions : 

<pre>
   "bootstrap-vue": "^0.16.1",
   "nuxt-helpers": "^0.10.0"
</pre>

the very opposite is true : 

nuxt.config.js:
<pre>
const NuxtHelpers = require('nuxt-helpers')

module.exports = NuxtHelpers(['bootstrap-vue'], {
...
})
</pre>

package.json:
<pre>
...
  "dependencies": {
    "bootstrap-vue": "^0.16.1",
    "nuxt": "latest",
    "nuxt-helpers": "^0.10.0"
  },
...
</pre>
